### ISSUE TITLE
systemd unit enhancements

### ISSUE THREAD

**Issue by JanWielemaker** [triska/letswicrypt#1]
Considering

```
ExecStart=/usr/local/bin/swipl server.pl --https --no-fork --user=you \
   --certfile=/var/www/xyz.com/server.crt \
   --keyfile=/var/www/xyz.com/server.key \
   --workers=16 --syslog=https \
   --cipherlist=DEFAULT:!RC4:!DES \
   --keep_alive_timeout=600
```

I have some suggestions:

  - I'd discourage `--user=you`.  Use a different user than your personal account, typically `www-data`.
  - `--syslog=https` is not needed with systemd.  Systemd will log messages of the deamon anyway.
  - `--keep_alive_timeout=600` is way too high.  This is the time a worker that completed an interaction
    while both parties want keep-alive will wait for the client to initiate a new request.   The default is 2
    seconds, which is plenty to ensure that multiple requests originating from loading a page are 
    handled using keep-alive.   Note that the value often keeps up to 6 workers occupied after loading
    a page.  If you use high values you must have a large number of workers, spawn each request on
    a thread or define the hooks can dynamically control the size of the worker pool.

**Comment by triska** [comment]
Many thanks, I have implemented all these changes and also enhanced the ciphers!
