### ISSUE TITLE
May want reload

### ISSUE THREAD

**Issue by JanWielemaker** [triska/letswicrypt#2]
If you add this line to the `https.service` file, you can use `systemd reload https` to make the server run
`make/0`.  Note that with recent 7.3.x versions you can do that safely while the server is running, provided you do not change the interface between predicates.  I.e., you can add, remove and edit clauses but you cannot add an argument or swap arguments reliably.

```
ExecReload=/bin/kill -s HUP $MAINPID
```

**Comment by triska** [comment]
Added, thank you!
