### ISSUE TITLE
Cannot run sample file server.pl

### ISSUE THREAD

**Issue by wouterbeek** [triska/letswicrypt#3]
When I run your sample file I get the following behavior:

```bash
$ swipl server.pl --port=4253
ERROR: No permission to fork process `main' (running_threads([pce]))
```

Any idea what could be wrong?

**Comment by wouterbeek** [comment]
Sorry, this was due to my `.swiplrc` file...

**Comment by koo5** [comment]
i keep running into this issue on another project, what was in your .swiplrc?:)
